#!/bin/sh
# mcsm container entrypoint.
#
# If /etc/mcsm/config.yaml is mounted from the host, use it verbatim.
# Otherwise, render it from environment variables (typically supplied
# via docker-compose `env_file: .env`). The plaintext token in
# MCSM_API_TOKEN is hashed with mcsm-tokens; only the hash is written
# to the file on disk.
set -eu

CONFIG=/etc/mcsm/config.yaml
DATA_DIR="${MCSM_DATA_DIR:-/var/lib/mcsm}"

# If the operator mounted their own config, respect it. Setting
# MCSM_RENDER_CONFIG=force re-renders even when one exists.
if [ -f "$CONFIG" ] && [ "${MCSM_RENDER_CONFIG:-}" != "force" ]; then
    echo "entrypoint: using existing $CONFIG"
    exec /usr/local/bin/mcsm --config "$CONFIG"
fi

# --- env-driven config render ---

require() {
    eval "v=\${$1:-}"
    if [ -z "$v" ]; then
        echo "entrypoint: $1 is required (set in .env)" >&2
        exit 1
    fi
}

require MCSM_API_TOKEN

INSTANCE="${MCSM_INSTANCE_NAME:-mcsm}"
BIND="${MCSM_API_BIND:-0.0.0.0:8124}"
ROOTS="${MCSM_DISCOVERY_ROOTS:-/mnt/servers}"
SCAN_INTERVAL="${MCSM_DISCOVERY_INTERVAL:-60s}"

SLOT_NAME="${MCSM_SLOT_NAME:-default}"
SLOT_PORT="${MCSM_SLOT_PORT:-25565}"
SLOT_PUBLIC="${MCSM_SLOT_PUBLIC_ADDRESS:-}"
SLOT_AUTO_MOUNT="${MCSM_SLOT_AUTO_MOUNT:-}"

LOG_LEVEL="${MCSM_LOG_LEVEL:-info}"
LOG_FORMAT="${MCSM_LOG_FORMAT:-json}"

AUDIT_ENABLED="${MCSM_AUDIT_ENABLED:-true}"
AUDIT_RETENTION="${MCSM_AUDIT_RETENTION:-720h}"
METRICS_ENABLED="${MCSM_METRICS_ENABLED:-true}"
METRICS_AUTH="${MCSM_METRICS_REQUIRE_AUTH:-false}"

TEMP_SENSOR="${MCSM_TEMP_SENSOR:-}"

# Hash the plaintext bearer token. The hash is what lives on disk; the
# plaintext lives only in the env (and ideally in your secrets manager).
TOKEN_HASH="$(printf '%s' "$MCSM_API_TOKEN" | /usr/local/bin/mcsm-tokens)"

mkdir -p "$(dirname "$CONFIG")"

{
    cat <<EOF
# Generated by mcsm container entrypoint at $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Edit by mounting your own config.yaml at /etc/mcsm/config.yaml.

instance:
  name: ${INSTANCE}
  data_dir: ${DATA_DIR}

api:
  bind: ${BIND}
  tokens:
    - name: default
      hash: "${TOKEN_HASH}"
      scopes: ["*"]
  cors:
    allowed_origins: []
  public_meta: true

discovery:
  roots:
EOF
    # Comma-separated list → YAML sequence.
    IFS=','
    for r in $ROOTS; do
        # Strip surrounding whitespace.
        r="$(printf '%s' "$r" | sed 's/^ *//;s/ *$//')"
        echo "    - ${r}"
    done
    unset IFS
    cat <<EOF
  scan_interval: ${SCAN_INTERVAL}

slots:
  - name: ${SLOT_NAME}
    port: ${SLOT_PORT}
EOF
    [ -n "$SLOT_PUBLIC" ]     && echo "    public_address: ${SLOT_PUBLIC}"
    [ -n "$SLOT_AUTO_MOUNT" ] && echo "    auto_mount: ${SLOT_AUTO_MOUNT}"
    cat <<EOF

peers:
  peers: []

EOF
    if [ -n "$TEMP_SENSOR" ]; then
        cat <<EOF
system:
  temperature:
    sensor: ${TEMP_SENSOR}

EOF
    fi
    cat <<EOF
logging:
  level: ${LOG_LEVEL}
  format: ${LOG_FORMAT}
  output: stdout

audit:
  enabled: ${AUDIT_ENABLED}
  retention: ${AUDIT_RETENTION}

metrics:
  enabled: ${METRICS_ENABLED}
  path: /metrics
  require_auth: ${METRICS_AUTH}
EOF
} > "$CONFIG"

echo "entrypoint: rendered $CONFIG from env vars"
exec /usr/local/bin/mcsm --config "$CONFIG"
